remote_theme: pages-themes/time-machine
plugins:
- jekyll-remote-theme
title: Aleesha Muslim
description: BS Computer Science student currently in 4th semester, passionate about coding, projects, and Azure cloud.
